version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unimarket
    ports:
      - "5432:5432"
    volumes:
      - unimarket_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "unimarket" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    image: unimarket:local
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ENV: development
      ENVIRONMENT: development
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@db:5432/unimarket"
      UNIMARKET_SECRET_KEY: "GgCtQ-5lhnQ9xWTUrf3wGzht5Qu8TwiDk9hIY8z4_S107Xp3pzCmNWup1yrais_p"
    volumes:
      - .:/app # только для разработки — горячая перезагрузка кода

volumes:
  unimarket_db_data:
