# pyproject.toml
[tool.black]
line-length = 88
target-version = ["py311"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "build",
    "dist", 
    "migrations",
    ".tox",
    "*.egg-info",
    "venv"
]
per-file-ignores = [
    "tests/*:S101"
]

[tool.bandit]
exclude_dirs = ['.venv', 'tests']
skips = ['B101', 'B104']   

[tool.isort]
profile = "black"
line_length = 88
filter_files = true
known_first_party = ["app", "tests"]

[tool.mutmut]
paths_to_mutate = "app/main.py"     # –ø–∞–ø–∫–∞ —Å –≤–∞—à–∏–º –∫–æ–¥–æ–º
tests_dir       = "tests"   # –ø–∞–ø–∫–∞ —Å —Ç–µ—Å—Ç–∞–º–∏
runner = "pytest -q --tb=short"
# üëá –ò—Å–∫–ª—é—á–∞–µ–º –Ω–µ–Ω—É–∂–Ω—ã–µ –¥–∏—Ä–µ–∫—Ç–æ—Ä–∏–∏ (—É—Å–∫–æ—Ä—è–µ—Ç –∞–Ω–∞–ª–∏–∑)
exclude = [
    "app/__init__.py",
    "app/config/",
    "app/migrations/",
    "venv/",
    "tests/"
]
timeout_factor = 4
use_coverage = true